default_title: "OpenLoge | Services Locaux Durables"
meta_description: "Retrouvez l'équipe d'experts de votre quartier dans la version beta de OpenLoge.fr!"
meta_image: "OpenLoge_Concept.png"
twitter_account: "@OpenLoge"
